# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HN2xQ8ub54xf40VTijPZ4yCaptL2zur5
"""

#PUNTOS 9 AL 20
#-----------------------------------------------------------------------------------
#Punto No 9
#Cree una función recursiva llamada cuenta_regresiva(n) que
#muestre los números desde n hasta 0. Debe detenerse correctamente
#cuando llegue al caso base. Nivel sugerido: Básico.

def cuenta_regresiva(n):
    if n < 0:
      print ("Fin del conteo Regresivo")
      return
    else:
      print("t -",n)
    cuenta_regresiva(n-1)

print("")
print("Punto No9")
n=int(input("Por favor ingrese el número desde el que quiere la cuenta regresiva: "))
cuenta_regresiva(n)
#----------------------------------------------------------------------------------
#Punto No 10
#Cree una función recursiva que calcule la suma de los números naturales desde 1
#hasta n. Por ejemplo, para n = 5 debe calcular 5 + 4 + 3 + 2 + 1. Nivel sugerido: Básico.

def sumarec(n):
    if n == 0:
        return 0
    else:
        return n + sumarec(n-1)

print("")
print("Punto No10 no usa la Formula de los n primeros números")
n=int(input("Por favor ingrese el número hasta el que quiera conocer la suma de los números naturales: "))
print("La suma de los números naturales desde 1 hasta ",n, "es de: ",sumarec(n))

#----------------------------------------------------------------------------------
#Punto No 11
#Desarrolle una función recursiva para calcular el factorial de un número entero no negativo.
# Valide la entrada antes de llamar la función.
#Pruebe el programa con 0, 1 y un número mayor que 1. Nivel sugerido: Intermedio.

def facto(n):
  if n==0 or n==1:
    return 1
  else:
    return n*facto(n-1)

print("")
print("Punto No11")
n=int(input("Por favor ingrese el número que quiere conocer su factorial: "))
print("El factorial de ",n," es: ",facto(n))


#----------------------------------------------------------------------------------
#Punto No 12
#Cree una función recursiva que calcule una potencia usando únicamente multiplicaciones.
#La función debe recibir base y exponente, donde el exponente es un entero mayor o igual a cero.
#Nivel sugerido: Intermedio.

def expon(b,e):
  if e==0:
    return 1
  else:
    return b*expon(b,e-1)
print("")
print("Punto No12")
b=int(input("Por favor ingrese el número que quiere usar como base: "))
e=int(input("Por favor ingrese el número que quiere usar como exponente (cantidad de veces que se multiplique la base): "))
print(f"EL resultado de {b} elevado a {e} ({b}^{e}) es: {expon(b,e)} ")

#----------------------------------------------------------------------------------
#Punto No 13
#Desarrolle una función recursiva que reciba un número entero positivo y cuente cuántos dígitos tiene.
#Ejemplo: 53829 tiene 5 dígitos. No convierta el número a texto para realizar el conteo. Nivel sugerido: Intermedio.

def contDig(n):
  if n<10:
    return 1
  else:
    return 1+contDig(n//10) #Recordar // es división entera

print("")
print("Punto No13")
n=int(input("Por favor ingrese un número entero positivo para determinar la cantidad de dígitos que tiene: "))
print(f"La cantidad de dígitos que tiene el número {n} es de: {contDig(n)}")

#----------------------------------------------------------------------------------
#Punto No 14
#Cree una función recursiva que reciba un número entero positivo y retorne la suma de sus dígitos.
#Ejemplo: para 4725 el resultado debe ser 18. Nivel sugerido: Intermedio.

def sumDig(n):
  if n<10:
    return n
  else:
    return n%10+sumDig(n//10) #%Retorno de residuo
print("")
print("Punto No14")
n=int(input("Por favor ingrese un número entero positivo para determinar cuanto suman sus dígitos: "))
print(f"La suma de los dígitos del número {n} es de: {sumDig(n)}")

#----------------------------------------------------------------------------------
#Punto No 15
#Diseñe una función recursiva que invierta una cadena de texto. Por ejemplo, si recibe "python", debe
#retornar "nohtyp". Explique en un comentario cuál es el caso base. Nivel sugerido: Intermedio.

def invpal(pal):
  if len(pal)<=1:
    return pal
  else:
    return pal[-1]+invpal(pal[:-1])


print("")
print("Punto No15")
pal=(input("Por favor ingrese el texto que quiera invertir: "))
print(f"La palabra {pal} al invertirla queda: {invpal(pal)}")
print("Actualmente se inicia desde la posción final de la palabra y la muestre al principio y cuando llegue a su primer elemento que lo retorne")

#----------------------------------------------------------------------------------
#Punto No 16
#Implemente una función recursiva que calcule el término n de la sucesión de Fibonacci. Muestre los
#primeros 10 términos llamando la función para cada posición. Nivel sugerido: Avanzado.

def sucfibo(n):
  if n==0 or n==1:
    return n
  else:
    return sucfibo(n-1)+sucfibo(n-2)


print("")
print("Punto No16")
print("los primeros 10 terminos de la sucesión de Fibonacci son: ")
for i in range(10):
  print(f"posición {i} es igual a {sucfibo(i)}")
print("Por favor NO usar números muy grandes por que se demora en procesar")
n=int(input("Por favor ingrese la posición para obtener el resultado de la sucesión de fibonacci: "))
print(f"La posición {n} refiere al valor: {sucfibo(n)}")

#----------------------------------------------------------------------------------
#Punto No 17
#Cree una tupla con números enteros y desarrolle una función recursiva que calcule la suma de
#todos sus elementos. La función debe recibir la tupla y una posición o índice que permita avanzar
#recursivamente. No use sum(). Nivel sugerido: Intermedio.

def sumtupl(t_sum,pos):
  if pos==len(t_sum):
    return 0
  else:
      return t_sum[pos]+sumtupl(t_sum,pos+1)

t_sum= (1,2,5,8,75,41,23,56)

print("")
print("Punto No17")
print("Los valores de la tupla son: ", t_sum)
print("La suma de los valores de la tupla es: ",sumtupl(t_sum,0))
print("Usando la función sum da: ",sum(t_sum))

#-----------------------------------------------------------------------------------
#Punto No18
#Diseñe una función recursiva que reciba una tupla y determine cuántas veces aparece un valor
#indicado por el usuario. No use el método count(). Al final, compare el resultado de su función con
#el resultado obtenido usando count(). Nivel sugerido: Avanzado.

def conttupl(t_al,pos,val):
  if pos==len(t_al):
    return 0
  else:
    if t_al[pos]==val:
      return 1+conttupl(t_al,pos+1,val)
    else:
      return conttupl(t_al,pos+1,val)

t_al= (1,2,5,8,75,41,23,56,89,1,0,2,12,11,5,9,89,10,20,35,47,51,63,98,100,99,57)

print("")
print("Punto No18")
val=int(input("Por favor ingrese el número que quiere validar cuantas veces aparece en la tupla, si aparece: "))
print("Los valores de la tupla son: ", t_al)
print(f"El valor {val} aparece: {conttupl(t_al,0,val)} ")
print("Usando la función count da: ",t_al.count(val))

#------------------------------------------------------------------------------------
#Punto No19
#Cree una tupla con nombres de estudiantes y desarrolle una función recursiva que busque un nombre
#dentro de ella. La función debe retornar la posición en la que se encuentra o -1 si el nombre no
#existe. No use in ni index() dentro de la función recursiva. Nivel sugerido: Avanzado.

def busnom(nomtup,pos,nom):
  if nom in nomtup:
    if nomtup[pos]==val:
      return pos+1
    else:
      return busnom(nomtup,pos+1,val)
  else:
      return -1

nomtup = ("Juan", "Luis","Martha","Laura", "Alejandro", "Maria","Samuel","Samantha", "Luisa","Julian", "Juliana","Victoria","Gerardo","Victor","Santiago","Omar","Otto","Valentina","Mary","Elena","Juan", "Pedro")
print("")
print("Punto No19")
print("--------------------------------------------------------------------------------------------------------------------------------------")
print("Acorde a la regla ortografica, la primer letra del nombre debe ir en mayuscula si ingresa todo en mínuscula el retorno será -1 siempre")
print("--------------------------------------------------------------------------------------------------------------------------------------")
val=input("Por favor ingrese el nombre que quiere validar si existe en la tupla (La posción que muestra iniciara en 1): ")
print("Los valores de la tupla son: ", nomtup)
print(f"El nombre {val} se encuentra en la posición: {busnom(nomtup,0,val)} ")
print("Recuerde que si la posicicón es -1, entonces, el nombre no esta en la lista o ingresó el nombre de manera erronea")

#------------------------------------------------------------------------------------
#Punto No20
#Una tienda registra sus ventas del día en una tupla de tuplas con la estructura:
#(producto, cantidad, precio_unitario)
#Por ejemplo:
#ventas = (
#( " Cuaderno " , 3 , 8500) ,
#( " Lapiz " , 5 , 1500) ,
#( " Regla " , 2 , 4000)
#)
#Construya un programa que incluya una función recursiva para calcular el valor total vendido.
#Después muestre el producto que generó el mayor ingreso, la cantidad total de unidades vendidas y
#el promedio de ingreso por producto. Para identificar el producto de mayor ingreso puede realizar un
#recorrido adicional sobre la tupla. Nivel sugerido: Avanzado.

def tuplprodu(product,pos):
  if pos==len(product):
    return 0
  else:
    nom, cant, pre = product[pos]
    valItem = pre * cant
    return valItem+tuplprodu(product,pos+1)

product= (
    ("Impresora_Epson", 5, 350000),
    ("Celular_HuaweiMAX", 10,1250000),
    ("Nevera", 6, 2750000),
    ("Teclado_Lenovo", 15, 125000),
    ("Horno_Electrico_5L", 8, 375000))

tot=tuplprodu(product,0)
print("")
print(f"El Total de los productos vendidos es: ${tot}")
print(f"El producto más vendido es: ${}")
print("Las unidades totales vendidas de todos los productos son: ",sum(i[1] for i in product))
print("El promedio de las ventas totales es: ", tot/ len(product)
print("")